export const defaultCategories = [
  {
    name: "Comida",
    description: "Gastos relacionados con alimentos y bebidas.",
    color: "#FF7F50",
    emoji: "🍔",
    isDefault: false,
  },
  {
    name: "Entretenimiento",
    description: "Gastos en actividades recreativas y ocio.",
    color: "#8A2BE2",
    emoji: "🎮",
    isDefault: false,
  },
  {
    name: "Salud",
    description: "Gastos médicos, seguros y bienestar.",
    color: "#3CB371",
    emoji: "🏥",
    isDefault: false,
  },
  {
    name: "Transporte",
    description: "Gastos en movilidad y transporte.",
    color: "#1E90FF",
    emoji: "🚗",
    isDefault: false,
  },
  {
    name: "Hogar",
    description: "Gastos relacionados con la vivienda y servicios.",
    color: "#DAA520",
    emoji: "🏠",
    isDefault: false,
  },
  {
    name: "Inversión",
    description: "Aportes y gastos en instrumentos financieros.",
    color: "#2E8B57",
    emoji: "📈",
    isDefault: false,
  },
  {
    name: "Sueldo",
    description: "Ingresos provenientes de remuneraciones.",
    color: "#32CD32",
    emoji: "💵",
    isDefault: false,
  },
  {
    name: "Transferencia",
    description: "Movimientos de dinero entre cuentas o terceros.",
    color: "#6495ED",
    emoji: "🔄",
    isDefault: false,
  },
  {
    name: "Otros",
    description: "Gastos o ingresos no categorizados.",
    color: "#A9A9A9",
    emoji: "❓",
    isDefault: true,
  },
];
